<a href="https://colab.research.google.com/github/ashishpatel26/Pytorch-Learning/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Torch
* Tensors are matrix-like data structures which are essential components in deep learning libraries and efficient computation. 
* **Graphical Processing Units (GPUs)** are especially effective at calculating operations between tensors, and this has spurred the surge in deep learning capability in recent times. 
* In **PyTorch**, tensors can be declared simply in a number of ways:
![](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)

**Constuct the 4 X 4 Matrix Empty Matrix**

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(4,4)
x

tensor([[1.4656e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00, 0.0000e+00]])

**Convert to numpy**

In [4]:
x.numpy()

array([[1.46564860e-35, 0.00000000e+00, 3.36311631e-44, 0.00000000e+00],
       [           nan, 0.00000000e+00, 1.15783705e+27, 1.13616057e+30],
       [7.15473767e+22, 4.58281141e+30, 1.21210947e+04, 7.18458933e+22],
       [9.21978159e-39, 7.03735270e+22, 0.00000000e+00, 0.00000000e+00]],
      dtype=float32)

**Size of the Tensor**

In [5]:
x.size()

torch.Size([4, 4])

From numpy to tensor

In [7]:
a = np.array([[5,7],[7,5]])
b = torch.from_numpy(a)
b

tensor([[5, 7],
        [7, 5]])

**Direct from Data**

In [8]:
data = [[1,5], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 5],
        [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [14]:
x_ones = torch.ones_like(x_data)
print(f"One Tensor : \n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor : \n{x_rand}")

One Tensor : 
tensor([[1, 1],
        [1, 1]])
Random Tensor : 
tensor([[0.3426, 0.2591],
        [0.9305, 0.0297]])


**Random and Constant Values**
* `shape` is a tuple of tensor dimensions.

In [16]:
shape = (2,3, )
print(f"Random Tensor : \n{torch.rand(shape)}")
print(f"Ones Tensor : \n{torch.ones(shape)}")
print(f"Zeros Tensor : \n{torch.zeros(shape)}")

Random Tensor : 
tensor([[0.4141, 0.2186, 0.1870],
        [0.4319, 0.6876, 0.6715]])
Ones Tensor : 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor : 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes
* Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [17]:
tensor = torch.rand(3,4)
print(f"Shape of the Tensor: {tensor.shape}")
print(f"Datatypes of the tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of the Tensor: torch.Size([3, 4])
Datatypes of the tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operation
* Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

In [21]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

**Basic Tensor Operation**
![](https://devblogs.nvidia.com/wp-content/uploads/2018/05/tesnor_core_diagram.png)

* Addition(`torch.add()`)
* Substraction(`torch.sub()`)
* Division(`torch.div()`)
* Multiplication(`torch.mul()`)

In [24]:
# Initialization
a = torch.rand(2,2)
b = torch.rand(2,2)

# Old Method
print(a + b)

# New Method
print(torch.add(a,b))

tensor([[0.8708, 0.9539],
        [0.8925, 1.3085]])
tensor([[0.8708, 0.9539],
        [0.8925, 1.3085]])


In [25]:
# Old Method
print(a - b)
# New Method
print(torch.sub(a,b))

tensor([[-0.0467, -0.6151],
        [-0.3391,  0.1613]])
tensor([[-0.0467, -0.6151],
        [-0.3391,  0.1613]])


In [26]:
# Old Method
print(a * b)

# New Method
print(torch.mul(a,b))

tensor([[0.1890, 0.1329],
        [0.1704, 0.4215]])
tensor([[0.1890, 0.1329],
        [0.1704, 0.4215]])


In [27]:
# Old Method
print(a / b)
# New Method
print(torch.div(a,b))

tensor([[0.8983, 0.2159],
        [0.4493, 1.2813]])
tensor([[0.8983, 0.2159],
        [0.4493, 1.2813]])


**Add x to y**

In [28]:
# a directly add to b and answer stored in b
print(f"b value before adding into a : \n{b}")
b.add_(a)
print(f"b value after adding into a : \n{b}")

b value before adding into a : 
tensor([[0.4587, 0.7845],
        [0.6158, 0.5736]])
b value after adding into a : 
tensor([[0.8708, 0.9539],
        [0.8925, 1.3085]])


**Standard Numpy like Indexing**

In [31]:
print(f"Column 0 : {a[:,0]}")
print(f"Column 1 : {a[:,1]}")

Column 0 : tensor([0.4121, 0.2767])
Column 1 : tensor([0.1694, 0.7349])


**Resizing**

In [42]:
x = torch.rand(4,4)
print(f"x: \n{x}")
y = x.view(16) # View is used to flatten the tensor
print(f"y : \n{y}")
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(f"z : \n{z}")
print(f"Size of x : {x.size()}\nSize of y : {y.size()}\nSize of z : {z.size()}")

x: 
tensor([[0.8652, 0.5624, 0.2412, 0.5409],
        [0.2230, 0.1732, 0.7071, 0.4156],
        [0.1426, 0.7136, 0.5535, 0.4098],
        [0.2926, 0.8536, 0.9006, 0.6357]])
y : 
tensor([0.8652, 0.5624, 0.2412, 0.5409, 0.2230, 0.1732, 0.7071, 0.4156, 0.1426,
        0.7136, 0.5535, 0.4098, 0.2926, 0.8536, 0.9006, 0.6357])
z : 
tensor([[0.8652, 0.5624, 0.2412, 0.5409, 0.2230, 0.1732, 0.7071, 0.4156],
        [0.1426, 0.7136, 0.5535, 0.4098, 0.2926, 0.8536, 0.9006, 0.6357]])
Size of x : torch.Size([4, 4])
Size of y : torch.Size([16])
Size of z : torch.Size([2, 8])


---
Note : Any operation that mutates a tensor in-place is post-fixed with an . For example: `x.copy_(y)`, `x.t_()`, will change x.
for more about tensor go on this link : https://pytorch.org/docs/stable/tensors.html


---