<a href="https://colab.research.google.com/github/ashishpatel26/Pytorch-Learning/blob/main/Pytorch_Basics_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Torch
* Tensors are matrix-like data structures which are essential components in deep learning libraries and efficient computation. 
* **Graphical Processing Units (GPUs)** are especially effective at calculating operations between tensors, and this has spurred the surge in deep learning capability in recent times. 
* In **PyTorch**, tensors can be declared simply in a number of ways:
![](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)

**Constuct the 4 X 4 Matrix Empty Matrix**

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(4,4)
x

tensor([[1.0971e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.7630e-36, 0.0000e+00]])

**Convert to numpy**

In [3]:
x.numpy()

array([[1.09713112e-35, 0.00000000e+00, 3.36311631e-44, 0.00000000e+00],
       [           nan, 0.00000000e+00, 1.15783705e+27, 1.13616057e+30],
       [7.15473767e+22, 4.58281141e+30, 1.21210947e+04, 7.18458933e+22],
       [9.21978159e-39, 7.03735270e+22, 3.76295946e-36, 0.00000000e+00]],
      dtype=float32)

**Size of the Tensor**

In [4]:
x.size()

torch.Size([4, 4])

From numpy to tensor

In [5]:
a = np.array([[5,7],[7,5]])
b = torch.from_numpy(a)
b

tensor([[5, 7],
        [7, 5]])

**Direct from Data**

In [6]:
data = [[1,5], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 5],
        [3, 4]])

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [7]:
x_ones = torch.ones_like(x_data)
print(f"One Tensor : \n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor : \n{x_rand}")

One Tensor : 
tensor([[1, 1],
        [1, 1]])
Random Tensor : 
tensor([[0.2983, 0.3927],
        [0.0039, 0.6277]])


**Random and Constant Values**
* `shape` is a tuple of tensor dimensions.

In [8]:
shape = (2,3, )
print(f"Random Tensor : \n{torch.rand(shape)}")
print(f"Ones Tensor : \n{torch.ones(shape)}")
print(f"Zeros Tensor : \n{torch.zeros(shape)}")

Random Tensor : 
tensor([[0.2058, 0.6316, 0.9871],
        [0.8376, 0.6633, 0.1986]])
Ones Tensor : 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor : 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes
* Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [9]:
tensor = torch.rand(3,4)
print(f"Shape of the Tensor: {tensor.shape}")
print(f"Datatypes of the tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of the Tensor: torch.Size([3, 4])
Datatypes of the tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operation
* Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

In [10]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

**Basic Tensor Operation**
![](https://devblogs.nvidia.com/wp-content/uploads/2018/05/tesnor_core_diagram.png)

* Addition(`torch.add()`)
* Substraction(`torch.sub()`)
* Division(`torch.div()`)
* Multiplication(`torch.mul()`)

In [11]:
# Initialization
a = torch.rand(2,2)
b = torch.rand(2,2)

# Old Method
print(a + b)

# New Method
print(torch.add(a,b))

tensor([[0.8596, 0.6325],
        [1.3522, 1.2812]])
tensor([[0.8596, 0.6325],
        [1.3522, 1.2812]])


In [12]:
# Old Method
print(a - b)
# New Method
print(torch.sub(a,b))

tensor([[ 0.4392, -0.0259],
        [ 0.1830, -0.0342]])
tensor([[ 0.4392, -0.0259],
        [ 0.1830, -0.0342]])


In [13]:
# Old Method
print(a * b)

# New Method
print(torch.mul(a,b))

tensor([[0.1365, 0.0998],
        [0.4487, 0.4101]])
tensor([[0.1365, 0.0998],
        [0.4487, 0.4101]])


In [14]:
# Old Method
print(a / b)
# New Method
print(torch.div(a,b))

tensor([[3.0897, 0.9213],
        [1.3130, 0.9480]])
tensor([[3.0897, 0.9213],
        [1.3130, 0.9480]])


**Add x to y**

In [15]:
# a directly add to b and answer stored in b
print(f"b value before adding into a : \n{b}")
b.add_(a)
print(f"b value after adding into a : \n{b}")

b value before adding into a : 
tensor([[0.2102, 0.3292],
        [0.5846, 0.6577]])
b value after adding into a : 
tensor([[0.8596, 0.6325],
        [1.3522, 1.2812]])


**Standard Numpy like Indexing**

In [16]:
print(f"Column 0 : {a[:,0]}")
print(f"Column 1 : {a[:,1]}")

Column 0 : tensor([0.6494, 0.7676])
Column 1 : tensor([0.3033, 0.6235])


**Resizing**

In [17]:
x = torch.rand(4,4)
print(f"x: \n{x}")
y = x.view(16) # View is used to flatten the tensor
print(f"y : \n{y}")
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(f"z : \n{z}")
print(f"Size of x : {x.size()}\nSize of y : {y.size()}\nSize of z : {z.size()}")

x: 
tensor([[0.8835, 0.5047, 0.2787, 0.9761],
        [0.9460, 0.3592, 0.1743, 0.8999],
        [0.2073, 0.2837, 0.7666, 0.8635],
        [0.7287, 0.7309, 0.7148, 0.4072]])
y : 
tensor([0.8835, 0.5047, 0.2787, 0.9761, 0.9460, 0.3592, 0.1743, 0.8999, 0.2073,
        0.2837, 0.7666, 0.8635, 0.7287, 0.7309, 0.7148, 0.4072])
z : 
tensor([[0.8835, 0.5047, 0.2787, 0.9761, 0.9460, 0.3592, 0.1743, 0.8999],
        [0.2073, 0.2837, 0.7666, 0.8635, 0.7287, 0.7309, 0.7148, 0.4072]])
Size of x : torch.Size([4, 4])
Size of y : torch.Size([16])
Size of z : torch.Size([2, 8])


---
Note : Any operation that mutates a tensor in-place is post-fixed with an . For example: `x.copy_(y)`, `x.t_()`, will change x.
for more about tensor go on this link : https://pytorch.org/docs/stable/tensors.html


---

**Joining Tensor**

In [19]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Multiplying Tensor**

In [22]:
# This is computes the element-wise product
print(f"tensor.mul(tensor) : \n {tensor.mul(tensor)}")
# Alternative syntax 
print(f"tensor * tensor : \n {tensor * tensor}")

tensor.mul(tensor) : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor * tensor : 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Matrix Multiplication**

In [23]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**Bridge with Numpy**

In [26]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [27]:
t.add_(1) #inplace with adding 1 to tensor
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
